# Generated by Django 4.1.1 on 2022-09-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='feed', max_length=50),
            preserve_default=False,
        ),
    ]
